### ISSUE TITLE
java.lang.IllegalArgumentException: Failed to detect origin method caller exception

### ISSUE THREAD

**Issue by theivupillai** [healenium/healenium-web#119]
<img width="960" alt="self healing error" src="https://user-images.githubusercontent.com/60739476/125164331-4babaa80-e1af-11eb-98d1-71110aa8f6d1.PNG">

I am getting the below error while trying to find element.

java.lang.IllegalArgumentException: Failed to detect origin method caller
	at com.epam.healenium.SelfHealingEngine.lambda$save$5(SelfHealingEngine.java:227)
	at java.util.Optional.orElseThrow(Unknown Source)
	at com.epam.healenium.SelfHealingEngine.save(SelfHealingEngine.java:227)
	at com.epam.healenium.SelfHealingEngine.savePath(SelfHealingEngine.java:132)
	at com.epam.healenium.SelfHealingEngine.savePath(SelfHealingEngine.java:120)
	at com.epam.healenium.handlers.proxy.BaseHandler.lookUp(BaseHandler.java:83)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:53)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at com.sun.proxy.$Proxy0.findElement(Unknown Source)
	at HealeniumPractice.selfHealing(HealeniumPractice.java:33)
	at HealeniumPractice.main(HealeniumPractice.java:20)

----
line number 20 in HealeniumPractice.java:
	void selfHealing() {

		try {
			//declare delegate
			delegate = new ChromeDriver();
			//create Self-healing driver
			driver = SelfHealingDriver.create(delegate);
			
			driver.get("http://www.google.co.in");
			driver.findElement(By.name("q")).sendKeys("hello"); #line number 20
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		
	}

**Comment by Thenappanlearnerforlife** [comment]
Even I am getting the same issue

**Comment by Aliaksei-Ashukha** [comment]
Hello @Thenappanlearnerforlife , @theivupillai 
Please create any directory under your **test.java** dir and put there HealeniumPractice.java
Thanks

**Comment by Aliaksei-Ashukha** [comment]
It fixed at 3.1.4 rev
