### ISSUE TITLE
A MismatchedInputException is thrown on attempt to heal

### ISSUE THREAD

**Issue by Jazzyekim** [healenium/healenium-web#123]
Hi,

I use: healenium-web, version 3-1
The backend is running on local docker:
```
CONTAINER ID   IMAGE                          COMMAND                  CREATED      STATUS      PORTS                                       NAMES
6dc2da98811b   healenium/hlm-backend:latest   "java -Djava.securit…"   3 days ago   Up 3 days   0.0.0.0:7878->7878/tcp, :::7878->7878/tcp   infra_healenium_1
a5c88a6c574e   postgres:11-alpine             "docker-entrypoint.s…"   3 days ago   Up 3 days   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   infra_db_1
```

But when I tried to run a test i got a warning and the exception:
```
Trying to heal...
[main] WARN com.epam.healenium.client.RestClient - Failed to make response
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.util.List<com.epam.healenium.treecomparing.Node>>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"pageContent":"","paths":[[{"tag":"html","index":0,"innerText":"Report Generator\nTest plan ID:\nEmail to:\nGet report","id":"","classes":"","other":{}},{"tag":"body","index":1,"innerText":"Report Generator\nTest plan ID:\nEmail to:\nGet report","id":"","classes":"text-center","other":{}},{"tag":"form","index":0,"innerText":"Report Generator\nTest plan ID:\nEmail to:\nGet report","id":"","classes":"form-signin","other":{"method":"post","action":"/report"}},{"tag":"input","index":3,"innerText":""[truncated 171 chars]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
```

did i overlook smth? Thank you

**Comment by sathya2388** [comment]
@GannaChernyshova Can you pelase help us with this one. ALso can you please tell how can we test  whether heal is happening or not.

**Comment by Aliaksei-Ashukha** [comment]
Hello @Jazzyekim,
Fixed in version 3.1.3
Please, use the last version and check docker-compose.yaml file. We added one more service.
Thanks

**Comment by Jazzyekim** [comment]
Hi @Aliaksei-Ashukha 
Thanks for fix. It seems to heal it now, but throws a lot of scary exceptions. For example in the console log to my test i got this:
`Trying to heal...
[main] WARN com.epam.healenium.client.RestClient - Failed to make imitate response
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8000
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
...
`

I have checked the logs of docker containers. The infra_db_1 has the following error:
`2021-08-13 13:47:25.717 UTC [1] LOG:  database system is ready to accept connections
2021-08-13 13:47:31.246 UTC [58] ERROR:  relation "healenium.databasechangeloglock" does not exist at character 22
2021-08-13 13:47:31.246 UTC [58] STATEMENT:  SELECT COUNT(*) FROM healenium.databasechangeloglock
`

The infra_healenium_1 has some errors as well
`2021-08-13 17:25:01.911 ERROR 1 - [Scheduler-1] e.p.PrometheusPushGatewayManager : Unable to push metrics to Prometheus Pushgateway java.net.SocketTimeoutException: connect timed out
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)`
and 
`2021-08-13 17:25:04.210 ERROR 1 - [878-exec-10] .c.c.C.[.[.[.[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.amazona
ws.SdkClientException: Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] with root cause sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)`
The last error indicates that there is some issue with some certificate. What it tries to call?

**Comment by Aliaksei-Ashukha** [comment]
Hello @Jazzyekim,

Please, update docker-compose file and restart containers.
healenium/hlm-backend:3.1.2
healenium/hlm-selector-imitator:1

**Comment by Jazzyekim** [comment]
Hi @Aliaksei-Ashukha 
I took docker-compose file from: https://raw.githubusercontent.com/healenium/healenium-client/master/example/docker-compose.yaml. It has a line `healenium/hlm-backend:latest` which i suppose will get the latest images. Not sure where the _imitator_ is set. 
Removed the images that I had and did `docker-compose up`, executed the test. When it heals I got the following errors to my console output:
```
Trying to heal...
[main] WARN com.epam.healenium.client.RestClient - Failed to make imitate response
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8000
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
...
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
```
` docker logs infra_db_1` doesn't show  anything interesting, but `docker logs infra_healenium_1` has an exception:
```
2021-08-20 10:54:30.189 WARN 1 - [7878-exec-6] c.e.h.c.HealingController : Session key is not present. Current issue would not be presented in any reports, but still available in replacement!
2021-08-20 10:54:30.507 INFO 1 - [7878-exec-6] Manager$PushGatewayTaskScheduler : Shutting down ExecutorService
2021-08-20 10:54:40.589 ERROR 1 - [Scheduler-1] e.p.PrometheusPushGatewayManager : Unable to push metrics to Prometheus Pushgateway java.net.SocketTimeoutException: connect timed out
at java.net.PlainSocketImpl.socketConnect(Nati at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
```

**Comment by Aliaksei-Ashukha** [comment]
Hi @Jazzyekim 

Please use actually docker-compose file from here:
 https://github.com/healenium/healenium-example-maven/blob/master/infra/docker-compose.yaml
