### ISSUE TITLE
com.epam.healenium.client.RestClient - Failed to make response

### ISSUE THREAD

**Issue by letsgetup** [healenium/healenium-web#124]
Hi Team, 

I am facing  below issue :  
> All services are running file and expected. Database with table created properly but healing and result tables are empty , in selector table get proper data in rows 

Request you to assist  me on this. 

Thanks,
Swapnil
 
***************  Error in Detail *********************************
Trying to heal...
[main] WARN com.epam.healenium.client.RestClient - Failed to make response
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.util.List<com.epam.healenium.treecomparing.Node>>` out of START_OBJECT token
 at [Source: (String)"{"pageContent":"","paths":[[{"tag":"html","index":0,"innerText":"Markup generator\nGenerate New Markup\nDefault label value\nClick me\nActions With Elements\nMake me invisible\nFor test FindElementWithinParent\nSecond","id":"","classes":"","other":{"lang":"en"}},{"tag":"body","index":1,"innerText":"Markup generator\nGenerate New Markup\nDefault label value\nClick me\nActions With Elements\nMake me invisible\nFor test FindElementWithinParent\nSecond","id":"","classes":"","other":{}},{"tag":"div","[truncated 1406 chars]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1168)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3188)
	at com.epam.healenium.client.RestClient.getLastValidPath(RestClient.java:154)
	at com.epam.healenium.SelfHealingEngine.lambda$getLastValidPaths$7(SelfHealingEngine.java:285)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.epam.healenium.SelfHealingEngine.getLastValidPaths(SelfHealingEngine.java:285)
	at com.epam.healenium.SelfHealingEngine.findNewLocations(SelfHealingEngine.java:197)
	at com.epam.healenium.service.impl.HealingServiceImpl.healLocators(HealingServiceImpl.java:94)
	at com.epam.healenium.service.impl.HealingServiceImpl.heal(HealingServiceImpl.java:53)
	at com.epam.healenium.handlers.proxy.BaseHandler.lookUp(BaseHandler.java:88)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:53)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at com.sun.proxy.$Proxy4.findElement(Unknown Source)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy8.click(Unknown Source)
	at pagefactory.MainPageWithFindBy.clickTestButton(MainPageWithFindBy.java:45)
	at healenium.MarkupTest.testButtonClickWithFindByAnnotationPage(MarkupTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)

**Comment by letsgetup** [comment]
Hi Team,

Could you please assist me on this ? 

Thanks,
Swapnil

**Comment by Aliaksei-Ashukha** [comment]
Hello @letsgetup ,
Fixed in version 3.1.3
Please, use the last version and check docker-compose.yaml file. We added one more service.
Thanks
