### ISSUE TITLE
java.lang.NoSuchMethodError: org.jsoup.nodes.Document.root()Lorg/jsoup/nodes/Node

### ISSUE THREAD

**Issue by VenkateshAchanta** [healenium/healenium-web#143]
We have integrated healenium our into framework during execution tests are failing with below Error. 

**Execution:**

java.lang.NoSuchMethodError: org.jsoup.nodes.Document.root()Lorg/jsoup/nodes/Node;
        at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:25)
        at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:273)
        at com.epam.healenium.SelfHealingEngine.findNearest(SelfHealingEngine.java:240)
        at com.epam.healenium.SelfHealingEngine.findNewLocations(SelfHealingEngine.java:198)
        at com.epam.healenium.service.impl.AbstractHealingServiceImpl.healLocator(AbstractHealingServiceImpl.java:54)
        at com.epam.healenium.service.impl.HealingServiceImpl.heal(HealingServiceImpl.java:38)
        at com.epam.healenium.handlers.proxy.BaseHandler.lookUp(BaseHandler.java:93)
        at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:58)
        at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
        at com.sun.proxy.$Proxy27.findElement(Unknown Source)

**Healenium Web Dependency:**

    <dependency>
		    <groupId>com.epam.healenium</groupId>
		    <artifactId>healenium-web</artifactId>
		    <version>3.1.5</version>
    </dependency>

**Comment by ElenaStepuro** [comment]
Hello @VenkateshAchanta and @rohitgera15 !
Please, updating the Jsoup version to 1.11.3 or higher for main project

**Comment by amoldsdev** [comment]
getting same error

**Comment by mohitniet** [comment]
I am getting below error while trying to heal in selenium web I am using below Maven dependcy
dependency>
    <groupId>com.epam.healenium</groupId>
    <artifactId>healenium-web</artifactId>
    <version>3.4.2</version>
</dependency>

<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.8.3</version>
</dependency>
org.jsoup.nodes.Document.root()Lorg/jsoup/nodes/Node

xception in thread "main" java.lang.NoSuchMethodError: org.jsoup.nodes.Document.root()Lorg/jsoup/nodes/Node;
	at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:25)
	at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:146)
	at com.epam.healenium.processor.HealingProcessor.execute(HealingProcessor.java:35)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:60)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at com.sun.proxy.$Proxy6.findElement(Unknown Source)

**Comment by mohitniet** [comment]
> We have integrated healenium our into framework during execution tests are failing with below Error.
> 
> **Execution:**
> 
> java.lang.NoSuchMethodError: org.jsoup.nodes.Document.root()Lorg/jsoup/nodes/Node; at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:25) at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:273) at com.epam.healenium.SelfHealingEngine.findNearest(SelfHealingEngine.java:240) at com.epam.healenium.SelfHealingEngine.findNewLocations(SelfHealingEngine.java:198) at com.epam.healenium.service.impl.AbstractHealingServiceImpl.healLocator(AbstractHealingServiceImpl.java:54) at com.epam.healenium.service.impl.HealingServiceImpl.heal(HealingServiceImpl.java:38) at com.epam.healenium.handlers.proxy.BaseHandler.lookUp(BaseHandler.java:93) at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:58) at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39) at com.sun.proxy.$Proxy27.findElement(Unknown Source)
> 
> **Healenium Web Dependency:**
> 
> ```
> <dependency>
> 	    <groupId>com.epam.healenium</groupId>
> 	    <artifactId>healenium-web</artifactId>
> 	    <version>3.1.5</version>
> </dependency>
> ```

is your issue resolved ?
