### ISSUE TITLE
[BUG]: Not healing the element using Healenium

### ISSUE THREAD

**Issue by sjvaidyan** [healenium/healenium-web#175]
### Describe the bug

Getting error as

java.lang.NoSuchMethodError: 'org.jsoup.nodes.Node org.jsoup.nodes.Document.root()'
at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:25)
  at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:122)
  at com.epam.healenium.processor.HealingProcessor.execute(HealingProcessor.java:32)
  at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
  at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
  at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
  at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:59)
  at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
  at com.sun.proxy.$Proxy13.findElement(Unknown Source)

### How to reproduce the issue

```shell
I am using Selenium java in my maven project.I have incoperated Healenium in my framework.When i tried to run to check the healing it shows Trying to Heal in the required element.But healing is not happening and throwing error as below
```

### Logs appeared during using Healenium

```shell
java.lang.NoSuchMethodError: 'org.jsoup.nodes.Node org.jsoup.nodes.Document.root()'
at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:25)
  at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:122)
  at com.epam.healenium.processor.HealingProcessor.execute(HealingProcessor.java:32)
  at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
  at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
  at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
  at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:59)
  at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
  at com.sun.proxy.$Proxy13.findElement(Unknown Source)
```

### Healenium Web version

3.2.1

### Healenium Backend version

Nil

### Platform

Java

**Comment by ElenaStepuro** [comment]
Hello @sjvaidyan Firstly you need to run the backend with docker containers. You can see setup tutorial here https://www.youtube.com/watch?v=Ed5HyfwZhq4

**Comment by Aliaksei-Ashukha** [comment]
Hi @sjvaidyan What jsoup version do you use in your project?

**Comment by mayukh-kant** [comment]
I had a similar issue. Got resolved after updating the jsop version to latest.
