### ISSUE TITLE
Getting error as "Failed to make response of 'getLastHealingData' request" with 3.2.3 version

### ISSUE THREAD

**Issue by automationspecialist05** [healenium/healenium-web#180]
Getting below issue with 3.2.3 version. Also does Healenium only work if the element locators are stored as variables in PageObject class?? Im using the locators as xpath directly in findElement command in the Test method.

ERROR LOG:::::
trying to heal...
[main] WARN com.epam.healenium.client.RestClient - Failed to make response of 'getLastHealingData' request.
java.io.IOException: unexpected end of stream on http://localhost:7878/...
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.epam.healenium.client.RestClient.getLastHealingData(RestClient.java:171)
        at com.epam.healenium.processor.GetLastHealingDataProcessor.execute(GetLastHealingDataProcessor.java:25)
        at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:41)
        at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:49)
        at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:58)
        at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
        at com.sun.proxy.$Proxy12.findElement(Unknown Source)
        at com.healenium.demo.AppTest.clickTestButton(AppTest.java:57)
        at com.healenium.demo.AppTest.shouldAnswerWithTrue(AppTest.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)    
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)   
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)   
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
        Suppressed: java.io.IOException: unexpected end of stream on http://localhost:7878/...
                ... 93 more
        Caused by: java.io.EOFException: \n not found: limit=0 content=?
                at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
                at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
                at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
                ... 92 more
Caused by: java.io.EOFException: \n not found: limit=0 content=?
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        ... 92 more
[main] WARN com.epam.healenium.handlers.proxy.BaseHandler - Error during findElement:
java.lang.NullPointerException
        at com.epam.healenium.processor.HealingProcessor.validate(HealingProcessor.java:22)
        at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:40)
        at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:49)
        at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:49)
        at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:58)
        at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
        at com.sun.proxy.$Proxy12.findElement(Unknown Source)
        at com.healenium.demo.AppTest.clickTestButton(AppTest.java:57)
        at com.healenium.demo.AppTest.shouldAnswerWithTrue(AppTest.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)    
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)   
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)   
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)

**Comment by automationspecialist05** [comment]
I noticed that [hlm-backend:3.2.0] keeps restarting as seen in Docker desktop.

LOG from Docker console:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/hlm-backend.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/hlm-backend.jar!/BOOT-INF/lib/slf4j-simple-1.7.28.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)

2022-03-17 16:38:11.308  INFO 1 - [       main] com.epam.healenium.Application   : Starting Application on c6b9cff66930 with PID 1 (/hlm-backend.jar started by root in /) 
2022-03-17 16:38:11.313  INFO 1 - [       main] com.epam.healenium.Application   : No active profile set, falling back to default profiles: default 
2022-03-17 16:38:12.908  INFO 1 - [       main] .RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode. 
2022-03-17 16:38:13.191  INFO 1 - [       main] .RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 263ms. Found 4 repository interfaces. 
2022-03-17 16:38:13.781  INFO 1 - [       main] elegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
2022-03-17 16:38:14.203  INFO 1 - [       main] o.s.b.w.e.t.TomcatWebServer      : Tomcat initialized with port(s): 7878 (http) 
2022-03-17 16:38:14.219  INFO 1 - [       main] o.a.c.core.StandardService       : Starting service [Tomcat] 
2022-03-17 16:38:14.220  INFO 1 - [       main] o.a.c.core.StandardEngine        : Starting Servlet engine: [Apache Tomcat/9.0.27] 
2022-03-17 16:38:14.464  INFO 1 - [       main] o.a.c.c.C.[.[localhost].[/]      : Initializing Spring embedded WebApplicationContext 
2022-03-17 16:38:14.464  INFO 1 - [       main] o.s.web.context.ContextLoader    : Root WebApplicationContext: initialization completed in 3055 ms 
2022-03-17 16:38:14.952  INFO 1 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Starting... 
2022-03-17 16:38:15.008 ERROR 1 - [       main] c.z.hikari.pool.HikariPool       : HikariPool-1 - Exception during pool initialization. org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)\n 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)\n 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)\n 	at org.postgresql.Driver.makeConnection(Driver.java:458)\n 	at org.postgresql.Driver.connect(Driver.java:260)\n 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)\n 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)\n 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)\n 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)\n 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)\n 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)\n 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:311)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)\n 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)\n 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)\n 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\n 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\n 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\n 	at com.epam.healenium.Application.main(Application.java:9)\n 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n 	at java.lang.reflect.Method.invoke(Method.java:498)\n 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)\n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)\n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)\n 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)\n Caused by: java.net.ConnectException: Connection refused (Connection refused)\n 	at java.net.PlainSocketImpl.socketConnect(Native Method)\n 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n 	at java.net.Socket.connect(Socket.java:607)\n 	at org.postgresql.core.PGStream.<init>(PGStream.java:75)\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)\n 	... 40 common frames omitted\n 
2022-03-17 16:38:15.011  WARN 1 - [       main] rvletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. 
2022-03-17 16:38:15.017  INFO 1 - [       main] o.a.c.core.StandardService       : Stopping service [Tomcat] 
2022-03-17 16:38:15.043  INFO 1 - [       main] nEvaluationReportLoggingListener : \n \n Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
2022-03-17 16:38:15.047 ERROR 1 - [       main] o.s.boot.SpringApplication       : Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)\n 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)\n 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)\n 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\n 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\n 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\n 	at com.epam.healenium.Application.main(Application.java:9)\n 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n 	at java.lang.reflect.Method.invoke(Method.java:498)\n 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)\n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)\n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)\n 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)\n Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.\n 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:316)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)\n 	... 26 common frames omitted\n Caused by: org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)\n 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)\n 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)\n 	at org.postgresql.Driver.makeConnection(Driver.java:458)\n 	at org.postgresql.Driver.connect(Driver.java:260)\n 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)\n 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)\n 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)\n 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)\n 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)\n 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)\n 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:311)\n 	... 28 common frames omitted\n Caused by: java.net.ConnectException: Connection refused (Connection refused)\n 	at java.net.PlainSocketImpl.socketConnect(Native Method)\n 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n 	at java.net.Socket.connect(Socket.java:607)\n 	at org.postgresql.core.PGStream.<init>(PGStream.java:75)\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)\n 	... 40 common frames omitted\n

**Comment by ElenaStepuro** [comment]
Hello @automationspecialist05 please, send the folder structure with init.sql file and docker-compose.yaml file
