### ISSUE TITLE
Locators are recorded but Healing does not work

### ISSUE THREAD

**Issue by Akhil423** [healenium/healenium-web#213]
### Describe the problem

Hi,

I have integrated healenium with our automation framework and able to record locators in healenium selector table after successful executions with framework but when there is "no such element found exception" element is not getting healed with recorded data in db.

help me out

### Healenium Web version

3.3.0

### Healenium Backend version

3.2.2

### Selenium version

3.141.59

### Platform

java

### Properties file

recovery-tries = 1
score-cap = 0.7
heal-enabled = true
hlm.server.url = http://localhost:7878
hlm.imitator.url = http://localhost:8000

### Logs appeared when using Healenium

```shell
(Session info: chrome=90.0.4430.212)
  (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Windows NT 10.0.19042 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 49 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'DESKTOP-', ip: '172.17.17.0', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, timeouts={implicit=0, pageLoad=300000, script=30000}, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:53925}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, webauthn:extension:largeBlob=true, unexpectedAlertBehaviour=ignore, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}), userDataDir=C:\Users\101421\AppData\Local\Temp\scoped_dir55260_2140061951}, takesHeapSnapshot=true, pageLoadStrategy=normal, strictFileInteractability=false, databaseEnabled=false, handlesAlerts=true, version=90.0.4430.212, browserConnectionEnabled=false, proxy={}, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true, webauthn:virtualAuthenticators=true}]
Session ID: eb08e67a7254657d1d559a1c254b955b
*** Element info: {Using=xpath, value=//inpu}
	at jdk.internal.reflect.GeneratedConstructorAccessor148.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at com.epam.healenium.processor.FindElementProcessor.execute(FindElementProcessor.java:24)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:41)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:58)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at com.sun.proxy.$Proxy129.findElement(Unknown Source)
```

**Comment by raghunadh10** [comment]
Hi @Akhil423  . could you please tell me on which type of website you are facing this issue . Is the website developed by  salesforce technology  ?

**Comment by Akhil423** [comment]
No @raghunadh10, application is developed using angular framework

**Comment by Alex-Reif** [comment]
Hi @Akhil423 , Please provide full logs and logs from the res services.
Also we recommend use the actual versions: https://github.com/healenium/healenium/releases

**Comment by Sisanda702** [comment]
Hello @Akhil423, I'm encountering the identical problem. Were you able to find a solution for it?

**Comment by harshajmera1992** [comment]
@raghunadh10 , is healenium not supported by salesforce applications ?

**Comment by Alex-Reif** [comment]
Healenium doesn't support Salesforce applications
