### ISSUE TITLE
[Need support]: Unable to self heal in selenium Maven Java getting NoSuchElementException

### ISSUE THREAD

**Issue by gokulencore114** [healenium/healenium-web#225]
### Describe the problem

Hi,
I have tried implementing self heal with selenium maven java project to locate the web element locators in the web page.
I tried the below link  full name field :
http://register.rediff.com/register/register.php?FormName=user_details
My docker is running and the container status is up. In the full name field locator is changing dynamically.I set up all settings like,healenium properties, I have provided the necessary snapshots . Kindly help me on the issue
<img width="1222" alt="Screenshot 2023-04-05 at 1 24 35 PM" src="https://user-images.githubusercontent.com/129938531/230017295-dd6f0e6b-6dae-4350-9cba-b31fbbbab147.png">
<img width="1368" alt="Screenshot 2023-04-05 at 1 25 27 PM" src="https://user-images.githubusercontent.com/129938531/230017466-275ef0a7-d6a1-4002-9ff8-d1f642c6c04d.png">
<img width="1229" alt="Screenshot 2023-04-05 at 1 27 10 PM" src="https://user-images.githubusercontent.com/129938531/230017925-9b29ef3e-cfb2-4e82-9d52-422fb9d176f1.png">
<img width="1257" alt="Screenshot 2023-04-05 at 1 27 57 PM" src="https://user-images.githubusercontent.com/129938531/230018109-7eebe20e-97e1-464a-92d6-dba14b94c103.png">

### Healenium Web version

3.4.0

### Healenium Backend version

NA

### Selenium version

4.8.1

### Platform

Java

### Properties file

recovery-tries=5
score-cap=.1
heal-enabled=true
hlm.server.url=http://localhost:7878
hlm.imitator.url=http://localhost:8000

### Logs appeared during using Healenium

```shell
/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=65418:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/jre/lib/rt.jar:/Users/gokulravichandran/Documents/Maven Demo project/target/classes:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-java/4.8.1/selenium-java-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-api/4.8.1/selenium-api-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/4.8.1/selenium-chrome-driver-4.8.1.jar:/Users/gokulravichandran/.m2/repository/com/google/auto/service/auto-service-annotations/1.0.1/auto-service-annotations-1.0.1.jar:/Users/gokulravichandran/.m2/repository/com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.jar:/Users/gokulravichandran/.m2/repository/com/google/auto/auto-common/1.2/auto-common-1.2.jar:/Users/gokulravichandran/.m2/repository/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:/Users/gokulravichandran/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/gokulravichandran/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/gokulravichandran/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/gokulravichandran/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar:/Users/gokulravichandran/.m2/repository/com/google/errorprone/error_prone_annotations/2.11.0/error_prone_annotations-2.11.0.jar:/Users/gokulravichandran/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-chromium-driver/4.8.1/selenium-chromium-driver-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-json/4.8.1/selenium-json-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v108/4.8.1/selenium-devtools-v108-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v109/4.8.1/selenium-devtools-v109-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v110/4.8.1/selenium-devtools-v110-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v85/4.8.1/selenium-devtools-v85-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/4.8.1/selenium-edge-driver-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/4.8.1/selenium-firefox-driver-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-http/4.8.1/selenium-http-4.8.1.jar:/Users/gokulravichandran/.m2/repository/dev/failsafe/failsafe/3.3.0/failsafe-3.3.0.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/4.8.1/selenium-ie-driver-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.8.1/selenium-remote-driver-4.8.1.jar:/Users/gokulravichandran/.m2/repository/com/beust/jcommander/1.82/jcommander-1.82.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-buffer/4.1.87.Final/netty-buffer-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-codec-http/4.1.87.Final/netty-codec-http-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-codec/4.1.87.Final/netty-codec-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-handler/4.1.87.Final/netty-handler-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-common/4.1.87.Final/netty-common-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport-classes-epoll/4.1.87.Final/netty-transport-classes-epoll-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport-classes-kqueue/4.1.87.Final/netty-transport-classes-kqueue-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport-native-epoll/4.1.87.Final/netty-transport-native-epoll-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.87.Final/netty-transport-native-kqueue-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.87.Final/netty-transport-native-unix-common-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport/4.1.87.Final/netty-transport-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-resolver/4.1.87.Final/netty-resolver-4.1.87.Final.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-api/1.22.0/opentelemetry-api-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-context/1.22.0/opentelemetry-context-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-exporter-logging/1.22.0/opentelemetry-exporter-logging-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-sdk-metrics/1.22.0/opentelemetry-sdk-metrics-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-sdk-logs/1.22.0-alpha/opentelemetry-sdk-logs-1.22.0-alpha.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-api-logs/1.22.0-alpha/opentelemetry-api-logs-1.22.0-alpha.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-sdk-common/1.22.0/opentelemetry-sdk-common-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.22.0/opentelemetry-sdk-extension-autoconfigure-spi-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure/1.22.0-alpha/opentelemetry-sdk-extension-autoconfigure-1.22.0-alpha.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-sdk-trace/1.22.0/opentelemetry-sdk-trace-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-sdk/1.22.0/opentelemetry-sdk-1.22.0.jar:/Users/gokulravichandran/.m2/repository/io/opentelemetry/opentelemetry-semconv/1.22.0-alpha/opentelemetry-semconv-1.22.0-alpha.jar:/Users/gokulravichandran/.m2/repository/io/ous/jtoml/2.0.0/jtoml-2.0.0.jar:/Users/gokulravichandran/.m2/repository/net/bytebuddy/byte-buddy/1.12.22/byte-buddy-1.12.22.jar:/Users/gokulravichandran/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/gokulravichandran/.m2/repository/org/asynchttpclient/async-http-client/2.12.3/async-http-client-2.12.3.jar:/Users/gokulravichandran/.m2/repository/org/asynchttpclient/async-http-client-netty-utils/2.12.3/async-http-client-netty-utils-2.12.3.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-codec-socks/4.1.60.Final/netty-codec-socks-4.1.60.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-handler-proxy/4.1.60.Final/netty-handler-proxy-4.1.60.Final.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport-native-epoll/4.1.60.Final/netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar:/Users/gokulravichandran/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.60.Final/netty-transport-native-kqueue-4.1.60.Final-osx-x86_64.jar:/Users/gokulravichandran/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar:/Users/gokulravichandran/.m2/repository/com/typesafe/netty/netty-reactive-streams/2.0.4/netty-reactive-streams-2.0.4.jar:/Users/gokulravichandran/.m2/repository/com/sun/activation/jakarta.activation/1.2.2/jakarta.activation-1.2.2.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-manager/4.8.1/selenium-manager-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/4.8.1/selenium-safari-driver-4.8.1.jar:/Users/gokulravichandran/.m2/repository/org/seleniumhq/selenium/selenium-support/4.8.1/selenium-support-4.8.1.jar:/Users/gokulravichandran/.m2/repository/com/epam/healenium/healenium-web/3.4.0/healenium-web-3.4.0.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin/3.0.0-M5/maven-surefire-plugin-3.0.0-M5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/surefire/maven-surefire-common/3.0.0-M5/maven-surefire-common-3.0.0-M5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/surefire/surefire-api/3.0.0-M5/surefire-api-3.0.0-M5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/surefire/surefire-logger-api/3.0.0-M5/surefire-logger-api-3.0.0-M5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/surefire/surefire-extensions-api/3.0.0-M5/surefire-extensions-api-3.0.0-M5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/surefire/surefire-booter/3.0.0-M5/surefire-booter-3.0.0-M5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/surefire/surefire-extensions-spi/3.0.0-M5/surefire-extensions-spi-3.0.0-M5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-toolchain/3.0-alpha-2/maven-toolchain-3.0-alpha-2.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.11.0/maven-artifact-transfer-0.11.0.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.jar:/Users/gokulravichandran/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar:/Users/gokulravichandran/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar:/Users/gokulravichandran/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar:/Users/gokulravichandran/.m2/repository/org/codehaus/plexus/plexus-java/1.0.5/plexus-java-1.0.5.jar:/Users/gokulravichandran/.m2/repository/org/ow2/asm/asm/7.2/asm-7.2.jar:/Users/gokulravichandran/.m2/repository/com/thoughtworks/qdox/qdox/2.0-M9/qdox-2.0-M9.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/surefire/surefire-shared-utils/3.0.0-M4/surefire-shared-utils-3.0.0-M4.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-artifact/3.8.4/maven-artifact-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-compat/3.8.4/maven-compat-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-model/3.8.4/maven-model-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-model-builder/3.8.4/maven-model-builder-3.8.4.jar:/Users/gokulravichandran/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-builder-support/3.8.4/maven-builder-support-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-settings/3.8.4/maven-settings-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-settings-builder/3.8.4/maven-settings-builder-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/codehaus/plexus/plexus-sec-dispatcher/2.0/plexus-sec-dispatcher-2.0.jar:/Users/gokulravichandran/.m2/repository/org/codehaus/plexus/plexus-cipher/2.0/plexus-cipher-2.0.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-core/3.8.4/maven-core-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/resolver/maven-resolver-spi/1.6.3/maven-resolver-spi-1.6.3.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar:/Users/gokulravichandran/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2-no_aop.jar:/Users/gokulravichandran/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-resolver-provider/3.8.4/maven-resolver-provider-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-repository-metadata/3.8.4/maven-repository-metadata-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/resolver/maven-resolver-api/1.6.3/maven-resolver-api-1.6.3.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.6.3/maven-resolver-util-1.6.3.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/resolver/maven-resolver-impl/1.6.3/maven-resolver-impl-1.6.3.jar:/Users/gokulravichandran/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar:/Users/gokulravichandran/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.5/org.eclipse.sisu.plexus-0.3.5.jar:/Users/gokulravichandran/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar:/Users/gokulravichandran/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.4.3/wagon-provider-api-3.4.3.jar:/Users/gokulravichandran/.m2/repository/org/apache/maven/maven-plugin-api/3.8.4/maven-plugin-api-3.8.4.jar:/Users/gokulravichandran/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar:/Users/gokulravichandran/.m2/repository/com/typesafe/config/1.4.2/config-1.4.2.jar:/Users/gokulravichandran/.m2/repository/com/epam/healenium/tree-comparing/0.4.11/tree-comparing-0.4.11.jar:/Users/gokulravichandran/.m2/repository/org/jsoup/jsoup/1.11.3/jsoup-1.11.3.jar:/Users/gokulravichandran/.m2/repository/org/apache/commons/commons-text/1.6/commons-text-1.6.jar:/Users/gokulravichandran/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar:/Users/gokulravichandran/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.4.1/jackson-databind-2.13.4.1.jar:/Users/gokulravichandran/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.4/jackson-annotations-2.13.4.jar:/Users/gokulravichandran/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.4/jackson-core-2.13.4.jar:/Users/gokulravichandran/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/Users/gokulravichandran/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/Users/gokulravichandran/.m2/repository/com/squareup/okhttp3/okhttp/4.9.3/okhttp-4.9.3.jar:/Users/gokulravichandran/.m2/repository/com/squareup/okio/okio/2.8.0/okio-2.8.0.jar:/Users/gokulravichandran/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.4.0/kotlin-stdlib-common-1.4.0.jar:/Users/gokulravichandran/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.4.10/kotlin-stdlib-1.4.10.jar:/Users/gokulravichandran/.m2/repository/com/squareup/okhttp3/logging-interceptor/4.10.0/logging-interceptor-4.10.0.jar:/Users/gokulravichandran/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.6.10/kotlin-stdlib-jdk8-1.6.10.jar:/Users/gokulravichandran/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.6.10/kotlin-stdlib-jdk7-1.6.10.jar:/Users/gokulravichandran/.m2/repository/org/jetbrains/annotations/23.0.0/annotations-23.0.0.jar:/Users/gokulravichandran/.m2/repository/org/mapstruct/mapstruct/1.4.2.Final/mapstruct-1.4.2.Final.jar:/Users/gokulravichandran/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar:/Users/gokulravichandran/.m2/repository/one/util/streamex/0.8.1/streamex-0.8.1.jar:/Users/gokulravichandran/.m2/repository/org/eclipse/jetty/jetty-server/10.0.10/jetty-server-10.0.10.jar:/Users/gokulravichandran/.m2/repository/org/eclipse/jetty/toolchain/jetty-servlet-api/4.0.6/jetty-servlet-api-4.0.6.jar:/Users/gokulravichandran/.m2/repository/org/eclipse/jetty/jetty-http/10.0.10/jetty-http-10.0.10.jar:/Users/gokulravichandran/.m2/repository/org/eclipse/jetty/jetty-util/10.0.10/jetty-util-10.0.10.jar:/Users/gokulravichandran/.m2/repository/org/eclipse/jetty/jetty-io/10.0.10/jetty-io-10.0.10.jar:/Users/gokulravichandran/.m2/repository/org/slf4j/slf4j-api/2.0.0-alpha6/slf4j-api-2.0.0-alpha6.jar:/Users/gokulravichandran/.m2/repository/org/hamcrest/hamcrest-core/2.2/hamcrest-core-2.2.jar:/Users/gokulravichandran/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar:/Users/gokulravichandran/.m2/repository/com/codeborne/selenide/6.1.1/selenide-6.1.1.jar:/Users/gokulravichandran/.m2/repository/com/codeborne/selenide-core/6.1.1/selenide-core-6.1.1.jar:/Users/gokulravichandran/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/gokulravichandran/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/Users/gokulravichandran/.m2/repository/org/apache/httpcomponents/client5/httpclient5/5.1.2/httpclient5-5.1.2.jar:/Users/gokulravichandran/.m2/repository/org/apache/httpcomponents/core5/httpcore5/5.1.2/httpcore5-5.1.2.jar:/Users/gokulravichandran/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/Users/gokulravichandran/.m2/repository/org/testcontainers/junit-jupiter/1.16.3/junit-jupiter-1.16.3.jar:/Users/gokulravichandran/.m2/repository/org/testcontainers/testcontainers/1.16.3/testcontainers-1.16.3.jar:/Users/gokulravichandran/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/Users/gokulravichandran/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar:/Users/gokulravichandran/.m2/repository/com/github/docker-java/docker-java-api/3.2.12/docker-java-api-3.2.12.jar:/Users/gokulravichandran/.m2/repository/com/github/docker-java/docker-java-transport-zerodep/3.2.12/docker-java-transport-zerodep-3.2.12.jar:/Users/gokulravichandran/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.8.2/junit-jupiter-engine-5.8.2.jar:/Users/gokulravichandran/.m2/repository/org/junit/platform/junit-platform-engine/1.8.2/junit-platform-engine-1.8.2.jar:/Users/gokulravichandran/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/Users/gokulravichandran/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.8.2/junit-jupiter-api-5.8.2.jar:/Users/gokulravichandran/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/Users/gokulravichandran/.m2/repository/org/junit/platform/junit-platform-commons/1.8.2/junit-platform-commons-1.8.2.jar:/Users/gokulravichandran/.m2/repository/org/mapstruct/mapstruct-processor/1.4.2.Final/mapstruct-processor-1.4.2.Final.jar:/Users/gokulravichandran/.m2/repository/io/github/bonigarcia/webdrivermanager/5.1.0/webdrivermanager-5.1.0.jar:/Users/gokulravichandran/.m2/repository/com/google/code/gson/gson/2.9.0/gson-2.9.0.jar:/Users/gokulravichandran/.m2/repository/com/github/docker-java/docker-java/3.2.13/docker-java-3.2.13.jar:/Users/gokulravichandran/.m2/repository/com/github/docker-java/docker-java-core/3.2.13/docker-java-core-3.2.13.jar:/Users/gokulravichandran/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.64/bcpkix-jdk15on-1.64.jar:/Users/gokulravichandran/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.64/bcprov-jdk15on-1.64.jar:/Users/gokulravichandran/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.30/jcl-over-slf4j-1.7.30.jar:/Users/gokulravichandran/.m2/repository/com/github/docker-java/docker-java-transport-httpclient5/3.2.13/docker-java-transport-httpclient5-3.2.13.jar:/Users/gokulravichandran/.m2/repository/com/github/docker-java/docker-java-transport/3.2.13/docker-java-transport-3.2.13.jar:/Users/gokulravichandran/.m2/repository/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar:/Users/gokulravichandran/.m2/repository/org/brotli/dec/0.1.2/dec-0.1.2.jar org.example.Main
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/Users/gokulravichandran/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 36915
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Apr 05, 2023 1:06:33 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 111, so returning the closest version found: 110
Exception in thread "main" org.openqa.selenium.NoSuchElementException: Failed to find element using By.name: name75443405
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2.1', java.version: '1.8.0_361'
Driver info: driver.version: unknown
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:72)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at com.sun.proxy.$Proxy6.findElement(Unknown Source)
	at org.example.Main.main(Main.java:24)
Caused by: java.lang.NullPointerException
	at com.epam.healenium.processor.GetReferenceElementsProcessor.populateUrlKey(GetReferenceElementsProcessor.java:70)
	at com.epam.healenium.processor.GetReferenceElementsProcessor.execute(GetReferenceElementsProcessor.java:52)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:60)
	... 3 more

Process finished with exit code 1
```

**Comment by Alex-Reif** [comment]
Hi @gokulencore114 , please update hlm-web to 3.4.2 and hlm-backend to 3.3.2
