### ISSUE TITLE
[BUG]: Unable to create driver using healenium

### ISSUE THREAD

**Issue by tarun-rogers** [healenium/healenium-web#228]
### Describe the bug

while creating the driver through healenium i am getting no such method  exception.

### How to reproduce the issue

```shell
I am using below code :

WebDriverManager.chromedriver().setup();
ChromeOptions options = new ChromeOptions();
options.addArguments("--incognito");
options.addArguments("--remote-allow-origins=*");
WebDriver selfHealingDriver = new ChromeDriver(options);
// chrome gets successfully launched at above step
WebDriver driver=SelfHealingDriver.create(selfHealingDriver);
// getting below exception at above step 
Caused by: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[])'
	at com.epam.healenium.client.RestClient.initReport(RestClient.java:262) ~[automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at com.epam.healenium.SelfHealingEngine.initReport(SelfHealingEngine.java:190) ~[automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at com.epam.healenium.SelfHealingDriver.callInitActions(SelfHealingDriver.java:66) ~[automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:42) ~[automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]

```

### Logs appeared during using Healenium

```shell
No
```

### Healenium Web version

3.4.2

### Healenium Backend version

image: healenium/hlm-backend:3.3.2

### Selenium version

4.7.2

### Platform

java

### Properties file

recovery-tries=1
score-cap=.6
heal-enabled=true
serverHost=localhost
serverPort=7878
imitatePort=8000

**Comment by tarun-rogers** [comment]
This issue is now resolved by updating most recent version of okhttp3 in my pom.
