### ISSUE TITLE
[Need support]: 

### ISSUE THREAD

**Issue by amang06fa** [healenium/healenium-web#235]
### Describe the problem

I am using healenium without docker and it works fine but when I go to http://localhost:7878/healenium/report/ 

I get the following error
![image](https://github.com/healenium/healenium-web/assets/124790922/3cff25c8-08f5-4f17-8d85-133ba1a01887)

### Healenium Web version

3.4.2

### Healenium Backend version

1.3.3

### Selenium version

4.9.0

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = 0.5
heal-enabled = true
hlm.server.url = http://localhost:7878
hlm.imitator.url = http://localhost:8000

### Logs appeared during using Healenium

```shell
2023-06-09 07:35:12.265 ERROR 25400 - [7878-exec-4] .c.c.C.[.[.[.[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1] with root cause java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1\n \n        at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4165)\n \n        at com.epam.healenium.service.impl.ReportServiceImpl.transformPath(ReportServiceImpl.java:132)\n \n     at com.epam.healenium.service.impl.ReportServiceImpl.lambda$buildReportRecords$4(ReportServiceImpl.java:115)\n \n         at java.base/java.lang.Iterable.forEach(Iterable.java:75)\n \n  at com.epam.healenium.service.impl.ReportServiceImpl.buildReportRecords(ReportServiceImpl.java:109)\n \n  at com.epam.healenium.service.impl.ReportServiceImpl.generate(ReportServiceImpl.java:71)\n \n   at com.epam.healenium.controller.ReportController.get(ReportController.java:40)\n \n      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n \n  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n \n at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n \n         at java.base/java.lang.reflect.Method.invoke(Method.java:568)\n \n      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)\n \n   at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)\n \n   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)\n \n     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)\n \n     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)\n \n  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n \n    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)\n \n         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)\n \n         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n \n       at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)\n \n       at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)\n \n      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n \n     at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)\n \n    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)\n \n         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n \n       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n \n    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n \n       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n \n         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n \n     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n \n       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n \n       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n \n         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n \n    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n \n       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n \n       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n \n         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)\n \n    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n \n     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n \n         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n \n       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n \n         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n \n     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n \n         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n \n       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)\n \n       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)\n \n      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)\n \n    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)\n \n   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n \n    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)\n \n  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)\n \n     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)\n \n        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\n \n        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)\n \n   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)\n \n     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n \n   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n \n       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n \n         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n \n      at java.base/java.lang.Thread.run(Thread.java:833)\n \n
```

**Comment by Alex-Reif** [comment]
Hi @amang06fa , Fixed at the hlm-backend 3.3.4
