### ISSUE TITLE
[Need support]: java.lang.NoSuchMethodError: 'org.openqa.selenium.remote.http.HttpClient org.openqa.selenium.devtools.CdpEndpointFinder.getHttpClient(org.openqa.selenium.remote.http.HttpClient$Factory, java.net.URI)'

### ISSUE THREAD

**Issue by himanshu910** [healenium/healenium-web#257]
### Describe the problem

Im getting below error , Kindly help please

java.lang.NoSuchMethodError: 'org.openqa.selenium.remote.http.HttpClient org.openqa.selenium.devtools.CdpEndpointFinder.getHttpClient(org.openqa.selenium.remote.http.HttpClient$Factory, java.net.URI)'
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:139)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:139)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at com.imm.esignplus.support.WebDriverFactory.get(WebDriverFactory.java:365)
	at com.imm.esignplus.support.WebDriverFactory.get(WebDriverFactory.java:225)
	at com.imm.esignplus.testscripts.OmniConnect.groundControl.test8(groundControl.java:486)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

### Healenium Web version

3.4.7

### Healenium Backend version

3.4.7

### Selenium version

4.14.0

### Platform

java

### Properties file

NA

### Logs appeared during using Healenium

```shell
NA
```

### Additional context

NA

**Comment by Alex-Reif** [comment]
Issue not related to healenium
