### ISSUE TITLE
[BUG]: java.lang.NoSuchMethodError: 'org.jsoup.nodes.Document org.jsoup.nodes.Document.normalise()' 	at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:24) AND 

### ISSUE THREAD

**Issue by mohanpalekar** [healenium/healenium-web#266]
### Describe the bug

Hi team 

I am running healenium-web with Java BDD and running into NoSuchMethodError error. I have seen issues reported before but that's not helping me. 

Healenium version:
<artifactId>healenium-web</artifactId>
<version>3.5.0</version>

Selenium Version
<artifactId>selenium-java</artifactId>
<version>4.18.1</version>

Jsoup version

		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.17.2</version>
		</dependency>

driver initialization:
WebDriverManager.chromedriver().setup();
			System.setProperty("webdriver.chrome.silentOutput", "true");

			final ChromeOptions options = new ChromeOptions();
			options.addArguments("--incognito");
			final WebDriver delegate = new ChromeDriver(options);

			/**
			 *  create Self-healing driver
			 */
			driver = SelfHealingDriver.create(delegate);

private final SelfHealingDriverWait wait = new SelfHealingDriverWait(driver,
			Duration.ofSeconds(Long.parseLong(props.getPropertyValueByKey("testDuration"))));

public WebElement waitUntilElementToBeClickable(final By element) {
		final WebElement webElement = wait.until(ExpectedConditions.elementToBeClickable(element));
		executionOrder(webElement);
		return webElement;
	}

Element I am trying to heal:
private final By searchBarXpath = By.className("desktop-searchBar");

![image](https://github.com/healenium/healenium-web/assets/97223992/710d1115-b470-4e9d-ae38-be3872c6d6b8)

![image](https://github.com/healenium/healenium-web/assets/97223992/8383b55a-aa44-454f-9b06-d895c323f6a0)

### How to reproduce the issue

```shell
I am running with pom or Runner class. I am running in debug mode and manually changing the locator on POM.  I have added a breakpoint and then I resume execution and it fails with jsoup error.

I have added latest jsoup dependency as well.
```

### Logs appeared during using Healenium

```shell
@AC-77 @BDD @REQ_AC-61 @TEST_AC-30 @TESTSET_AC-8 @TESTSET_AC-29 @AC_30 @BDD1 @Sanity
Scenario: Verify that the Red Tape Search on Myntra works fine # 2_Search On Myntraaa.feature:7
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 122.0.6261.69 (resolved driver for Chrome 122)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\NIKITA\.cache\selenium\chromedriver\win64\122.0.6261.69\chromedriver.exe
Done
  Given I am on Myntra's Website                               # com.automation.advancedaeleniumbddpmd.stepdefinition.MyntraSearchPageStepDefinition.iAmOnMyntra()
[main] WARN healenium - Failed to find an element using locator By.className: desktop-searchBar
[main] WARN healenium - Reason: no such element: Unable to locate element: {"method":"css selector","selector":".desktop\-searchBar"}
  (Session info: chrome=122.0.6261.70)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [a33b4962c6eeae711f3501234b4f8a48, findElement {using=class name, value=desktop-searchBar}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 122.0.6261.70, chrome: {chromedriverVersion: 122.0.6261.69 (81bc525b6a36..., userDataDir: C:\Users\NIKITA\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:51003}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:51003/devtoo..., se:cdpVersion: 122.0.6261.70, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: a33b4962c6eeae711f3501234b4f8a48
[main] WARN healenium - Trying to heal...
  When I enter Red Tape Shoes in search bar                    # com.automation.advancedaeleniumbddpmd.stepdefinition.MyntraSearchPageStepDefinition.iSearchUsingSearchBar(java.lang.String)
      java.lang.NoSuchMethodError: 'org.jsoup.nodes.Document org.jsoup.nodes.Document.normalise()'
	at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:24)
	at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:144)
	at com.epam.healenium.processor.HealingProcessor.execute(HealingProcessor.java:35)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:63)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at jdk.proxy2/jdk.proxy2.$Proxy20.findElement(Unknown Source)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:194)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:190)
	at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:627)
	at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:624)
	at com.epam.healenium.SelfHealingDriverWait.until(SelfHealingDriverWait.java:44)
	at com.automation.advancedaeleniumbddpmd.utilities.ActionEngine.waitUntilElementToBeClickable(ActionEngine.java:78)
	at com.automation.advancedaeleniumbddpmd.pageobjects.MyntraPageObjects.searchOnMyntra(MyntraPageObjects.java:22)
	at com.automation.advancedaeleniumbddpmd.stepdefinition.MyntraSearchPageStepDefinition.iSearchUsingSearchBar(MyntraSearchPageStepDefinition.java:32)
	at ✽.I enter Red Tape Shoes in search bar(file:///C:/Users/NIKITA/eclipse-workspace/AdvancedSeleniumBDDPMD/./2_Search%20On%20Myntraaa.feature:9)

  Then I press Enter button                                    # com.automation.advancedaeleniumbddpmd.stepdefinition.MyntraSearchPageStepDefinition.iPressEnterButton()

    Embedding Verify that the Red Tape Search on Myntra works fine [image/png 449271 bytes]

Feb 24, 2024 11:07:43 AM net.masterthought.cucumber.ReportParser parseJsonFiles
INFO: File 'target\JSON\cucumber.json' contains 1 feature(s)
```

### Expected behavior

Healing should have been performed

### Actual behavior

Healing is not done

### Healenium Web version

3.5.0

### Healenium Backend version

3.4.4

### Selenium version

4.18.1

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = .6
heal-enabled = true
hlm.server.url = http://localhost:7878
hlm.imitator.url = http://localhost:8000

**Comment by mohanpalekar** [comment]
![image](https://github.com/healenium/healenium-web/assets/97223992/a79b8bec-198a-4d21-a048-eb68a91adac5)

**Comment by Alex-Reif** [comment]
Hi @mohanpalekar , Thanks to find compatibility issue with actual jsoup lib. We will fix it in the new version and let you know

**Comment by longk15t** [comment]
I got same error with healenium-web 3.5.1 and selenium 4.18.1 and jsoup 1.17.2
should we downgrade the jsoup version ?

**Comment by mohitniet** [comment]
> Hi @mohanpalekar , Thanks to find compatibility issue with actual jsoup lib. We will fix it in the new version and let you know

is this fixed? Whats the solution we did?
