### ISSUE TITLE
[BUG]: ERROR healenium - Failed to get element node path! com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from [Unavailable value] (token `JsonToken.NOT_AVAILABLE`)  at [Source: UNKNOWN; byte offset: #UNKNOWN]

### ISSUE THREAD

**Issue by mitchellhwright** [healenium/healenium-web#270]
### Describe the bug

Seeing Healenium exception when finding certain xpath locators like this:
`//div[contains(text(),'Default Text')]/../../*[local-name()='svg']`

Exception/Stack Trace:
```
ERROR healenium - Failed to get element node path!
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from [Unavailable value] (token `JsonToken.NOT_AVAILABLE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1473) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1456) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:48) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3438) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.epam.healenium.service.NodeService.toNode(NodeService.java:76) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.service.NodeService.getNodePath(NodeService.java:54) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.SelfHealingEngine.lambda$getNodePath$0(SelfHealingEngine.java:121) ~[healenium-web-3.5.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747) ~[na:na]
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.epam.healenium.SelfHealingEngine.getNodePath(SelfHealingEngine.java:122) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.SelfHealingEngine.saveElements(SelfHealingEngine.java:104) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.processor.FindElementProcessor.execute(FindElementProcessor.java:25) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:63) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39) ~[healenium-web-3.5.0.jar:na]
	at com.sun.proxy.$Proxy44.findElement(Unknown Source) ~[na:na]
```

### How to reproduce the issue

```shell
Webdriver is started by WebDriverManager and this error is seen in Firefox and Chrome:

14:32:41.643 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager - Using WebDriverManager 5.7.0
14:32:41.994 [main] DEBUG i.g.b.wdm.cache.ResolutionCache - Resolution firefox=118 in cache (valid until 15:26:08 16/04/2024 EDT)
14:32:41.998 [main] DEBUG i.g.b.wdm.cache.ResolutionCache - Resolution firefox118=0.34.0 in cache (valid until 14:26:08 17/04/2024 EDT)
14:32:41.999 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using geckodriver 0.34.0 (resolved driver for Firefox 118)
14:32:42.042 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager - Driver geckodriver 0.34.0 found in cache
14:32:42.045 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as /Users/m.wright/.cache/selenium/geckodriver/mac64/0.34.0/geckodriver
14:32:42.045 [main] DEBUG i.g.b.wdm.versions.VersionDetector - Detecting firefox path using the commands database
14:32:42.265 [main] DEBUG i.g.b.wdm.versions.VersionDetector - The path of firefox is /Applications/Firefox.app/Contents/MacOS/firefox
[14:32:42:272] █ █  WebDriverManager setup firefox with driver v0.34.0. Change this with parameter 'browserVersion' █ █ 
[14:32:45:636] java -jar selenium-server-4.18.1.jar standalone --port 4321 --log-level SEVERE
```
```


### Logs appeared during using Healenium

```shell
DEBUG healenium - [Save Elements] Request: (POST) . Request body: RequestDto(locator=//div[contains(text(),'Text ID')]/../../*[local-name()='svg'], type=By.xpath, className=com.cvent.automation.driver.CventDriver, methodName=remoteFindElement, command=findElement, results=null, usedResult=null, url=https://app.t2.cvent.com/Subscribers/Admin/Portals2/LanguageManagement/Index/View/, elementIds=null, enableHealing=false, sessionId=75054558-3098-4a08-a897-b8cc475a9d00)
[14:33:43:581] 	SELF HEALING WAIT: Clickability of WebElementProxyHandler Located With • xpath = //div[contains(text(),'Text ID')]/../../*[local-name()='svg'] •


█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ VERIFICATION PASSED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
█ TEST: Stargate_Language_Management•Stargate Languages Management                                           █
█ STEP 38 ▐ ACTION: VerifyExistence▐ OBJECT: StargatePortals.Portals.btnLanguagesTabTextIDSort▐              █
█ EXISTENCE VERIFICATION OF • xpath = //div[contains(text(),'Text ID')]/../../*[local-name()='svg'] • PASSED █
█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ VERIFICATION PASSED ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█

[14:33:43:592] STEP 39 ▐ ACTION: VerifyExistence▐ OBJECT: StargatePortals.Portals.btnLanguagesDefaultTextSort▐ 
14:33:44.199 [] ERROR healenium - Failed to get element node path!
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from [Unavailable value] (token `JsonToken.NOT_AVAILABLE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1473) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1456) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:48) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3438) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.epam.healenium.service.NodeService.toNode(NodeService.java:76) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.service.NodeService.getNodePath(NodeService.java:54) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.SelfHealingEngine.lambda$getNodePath$0(SelfHealingEngine.java:121) ~[healenium-web-3.5.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747) ~[na:na]
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.epam.healenium.SelfHealingEngine.getNodePath(SelfHealingEngine.java:122) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.SelfHealingEngine.saveElements(SelfHealingEngine.java:104) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.processor.FindElementProcessor.execute(FindElementProcessor.java:25) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:63) ~[healenium-web-3.5.0.jar:na]
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39) ~[healenium-web-3.5.0.jar:na]
	at com.sun.proxy.$Proxy44.findElement(Unknown Source) ~[na:na]
	at com.cvent.automation.driver.CventDriver.remoteFindElement(CventDriver.java:295) ~[classes/:na]
	at com.cvent.automation.driver.conditions.CventConditions.findElement(CventConditions.java:293) ~[classes/:na]
	at com.cvent.automation.driver.conditions.CventConditions$13.lambda$apply$0(CventConditions.java:592) ~[classes/:na]
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[na:na]
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528) ~[na:na]
	at com.cvent.automation.driver.conditions.CventConditions$13.apply(CventConditions.java:588) ~[classes/:na]
	at com.cvent.automation.driver.conditions.CventConditions$13.apply(CventConditions.java:577) ~[classes/:na]
	at com.cvent.automation.driver.conditions.CventConditions$12.apply(CventConditions.java:562) ~[classes/:na]
	at com.cvent.automation.driver.conditions.CventConditions$12.apply(CventConditions.java:548) ~[classes/:na]
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:203) ~[selenium-support-4.18.1.jar:na]
	at com.cvent.automation.driver.conditions.CventWait.until(CventWait.java:90) ~[classes/:na]
	at com.cvent.automation.objects.ICventUiObject.getWebElement(ICventUiObject.java:78) ~[classes/:na]
	at com.cvent.automation.objects.FindCventObject.getWebElement(FindCventObject.java:94) ~[classes/:na]
	at com.cvent.automation.objects.ICventUiObject.getWebElement(ICventUiObject.java:62) ~[classes/:na]
	at com.cvent.automation.converters.CventObject.getWebElement(CventObject.java:71) ~[classes/:na]
	at com.cvent.automation.action.ICventUiAction.getWebElement(ICventUiAction.java:51) ~[classes/:na]
	at com.cvent.automation.action.ICventUiAction.getWebElement(ICventUiAction.java:47) ~[classes/:na]
	at com.cvent.automation.action.ICventUiAction.getWebElement(ICventUiAction.java:31) ~[classes/:na]
	at com.cvent.automation.action.concrete.VerifyElementExistence.accept(VerifyElementExistence.java:36) ~[classes/:na]
	at com.cvent.automation.action.concrete.VerifyElementExistence.accept(VerifyElementExistence.java:23) ~[classes/:na]
	at com.cvent.automation.action.ActionType.accept(ActionType.java:149) ~[classes/:na]
	at com.cvent.automation.action.ActionType.accept(ActionType.java:26) ~[classes/:na]
	at com.cvent.automation.test.steps.TestStep.runAction(TestStep.java:443) ~[classes/:na]
	at com.cvent.automation.test.steps.TestStep.run(TestStep.java:336) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at com.cvent.automation.hooks.CucumberHooks.runAccumulatedActions(CucumberHooks.java:125) ~[classes/:na]
	at com.cvent.automation.hooks.CucumberHooks.after(CucumberHooks.java:102) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66) ~[cucumber-java-6.10.4.jar:6.10.4]
	at io.cucumber.java.Invoker.invoke(Invoker.java:24) ~[cucumber-java-6.10.4.jar:6.10.4]
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47) ~[cucumber-java-6.10.4.jar:6.10.4]
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:59) ~[cucumber-java-6.10.4.jar:6.10.4]
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.core.runner.TestStep.run(TestStep.java:64) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.core.runner.TestCase.run(TestCase.java:110) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:73) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$0(TestNGCucumberRunner.java:117) ~[cucumber-testng-6.10.4.jar:6.10.4]
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117) ~[cucumber-core-6.10.4.jar:6.10.4]
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:114) ~[cucumber-testng-6.10.4.jar:6.10.4]
	at com.cvent.automation.runners.CucumberTestRunner.testPerScenario(CucumberTestRunner.java:227) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```
```


### Expected behavior

Wouldn't expect Healenium to dump this ERROR exception.  I can ignore it but I don't know what about that locator is causing it to choke on that xpath.

### Actual behavior

Process the locator `//div[contains(text(),'Default Text')]/../../*[local-name()='svg']` and store it in the Healenium db

### Healenium Web version

None

### Healenium Backend version

3.4.5

### Selenium version

4.18.1

### Platform

Java

### Properties file

recovery-tries=1 score-cap=.85 heal-enabled=true serverHost=localhost serverPort=7878 imitatePort=8000

### Additional context

_No response_

**Comment by Alex-Reif** [comment]
Hi @mitchellhwright Issue fixed in the v 3.5.4
