### ISSUE TITLE
[BUG]: java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasInputDevices

### ISSUE THREAD

**Issue by umredkarabhijeet** [healenium/healenium-web#278]
### Describe the bug

Hi, I am getting following error on this line :-

driver = SelfHealingDriver.create(delegate);

java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasInputDevices
at com.epam.healenium.utils.ProxyFactory.createDriverProxy(ProxyFactory.java:35)
at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:45)
at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:34)

my selenium version is 4.11.0 and healenium-web is 3.2.0.
Could someone help to fix above exception?

### How to reproduce the issue

```shell
my selenium version is 4.11.0 and healenium-web is 3.2.0.
Could someone help to fix above exception?
```

### Logs appeared during using Healenium

```shell
java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasInputDevices
at com.epam.healenium.utils.ProxyFactory.createDriverProxy(ProxyFactory.java:35)
at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:45)
at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:34)
```

### Healenium Web version

3.2.0

### Healenium Backend version

3.2.0

### Selenium version

4.11.0

### Platform

JAVA

**Comment by umredkarabhijeet** [comment]
@Alex-Reif any updates on this
