### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by shiva4983** [healenium/healenium-web#58]
Hi 
web.get("https://google.ca");
		web.findElement(By.xpath("//*[@id=\"tsf\"]/div[2]/div[1]/div[1]/div/div[2]/input")).sendKeys("test");

I am getting NoClassDefFoundError while using findElement(By.locator).

java.lang.NoClassDefFoundError: org/openqa/selenium/internal/WrapsElement
	at com.epam.healenium.utils.ProxyFactory.createWebElementProxy(ProxyFactory.java:43)
	at com.epam.healenium.handlers.proxy.BaseHandler.wrapElement(BaseHandler.java:209)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.lambda$invoke$0(SelfHealingProxyInvocationHandler.java:37)
	at java.util.Optional.map(Optional.java:215)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:37)
	at com.sun.proxy.$Proxy28.findElemen

I am using healenium-web 2.0.5 version

**Comment by shiva4983** [comment]
its a Selenium issue. Selenium 4 does have issue with selenium 3.14 it got resolved.
