### ISSUE TITLE
Failed to detect origin method caller

### ISSUE THREAD

**Issue by kaviarasan96** [healenium/healenium-web#59]
Im facing this issue when i try to run test.

**Comment by Aliaksei-Ashukha** [comment]
Hi @kaviarasan96,

Please use the default Maven or Gradle test runs. Healenium do not trigger report generation for test runs from TestNG or Junit.

**Comment by skptricks** [comment]
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"D:\program files\UFT\bin\java_shared\classes\jasmine.jar"
Starting ChromeDriver 88.0.4324.27 (6347fe8bf1e48bd0c54d07dc55ca011cf40861c9-refs/branch-heads/4324@{#450}) on port 6657
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Feb 16, 2021 9:27:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.IllegalArgumentException: Failed to detect origin method caller
	at com.epam.healenium.SelfHealingEngine.lambda$savePath$1(SelfHealingEngine.java:99)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at com.epam.healenium.SelfHealingEngine.savePath(SelfHealingEngine.java:99)
	at com.epam.healenium.handlers.proxy.BaseHandler.lookUp(BaseHandler.java:67)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:51)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:37)
	at com.sun.proxy.$Proxy0.findElement(Unknown Source)
	at Test.main(Test.java:37)

**Comment by Aliaksei-Ashukha** [comment]
Hi @skptricks , 
Could you provide git link to your project? I'll check how you find element.
